use super::{buffer_len, Display};
use super::{DisplayRotation, InitStep};
use crate::color::Color;
use crate::{cmd, driver::Ssd1680Driver, flag, interface::SpiDisplayInterface};
use display_interface::DisplayError;
use embedded_graphics::{pixelcolor::BinaryColor, prelude::*};
use embedded_hal::delay::DelayNs;
use embedded_hal::digital::{InputPin, OutputPin};
use embedded_hal::spi::SpiDevice;
use log::debug;

/// Display width for 2.13in panel
pub const WIDTH: u16 = 122;
/// Display height for 2.13in panel
pub const HEIGHT: u16 = 255;

/// Init sequence for this panel
pub const INIT_SEQUENCE: &[InitStep] = &[
    InitStep::SWReset,
    InitStep::WaitUntilIdle,
    // driver output ctrl with height-1 will be generated by DriverControl step
    InitStep::DriverControl,
    InitStep::CmdData(
        cmd::Cmd::DATA_ENTRY_MODE,
        &[flag::Flag::DATA_ENTRY_INCRY_INCRX],
    ),
    InitStep::CmdData(
        cmd::Cmd::BORDER_WAVEFORM_CTRL,
        &[flag::Flag::BORDER_WAVEFORM_FOLLOW_LUT | flag::Flag::BORDER_WAVEFORM_LUT1],
    ),
    InitStep::CmdData(cmd::Cmd::TEMP_CONTROL, &[flag::Flag::INTERNAL_TEMP_SENSOR]),
    InitStep::CmdData(cmd::Cmd::DISPLAY_UPDATE_CTRL1, &[0x00, 0x80]),
    InitStep::UseFullFrame,
];

/// Driver for a 250x122 panel (2.13in WeAct Studio)
pub struct WeActStudio2in13<SPI, BSY, DC, RST>
where
    SPI: SpiDevice,
    BSY: InputPin,
    DC: OutputPin,
    RST: OutputPin,
{
    interface: SpiDisplayInterface<SPI, BSY, DC, RST>,
}

impl<SPI, BSY, DC, RST> WeActStudio2in13<SPI, BSY, DC, RST>
where
    SPI: SpiDevice,
    BSY: InputPin,
    DC: OutputPin,
    RST: OutputPin,
{
    /// Create a new WeAct Studio 2.13" driver
    pub fn new(spi: SPI, busy: BSY, dc: DC, rst: RST) -> Result<Self, DisplayError> {
        let interface = SpiDisplayInterface::new(spi, busy, dc, rst);
        Ok(Self { interface })
    }

    /// Update black & white buffer and refresh the display in one command
    pub fn update_and_display_bw(
        &mut self,
        buffer: &[u8],
        delay: &mut impl DelayNs,
    ) -> Result<(), DisplayError> {
        self.init(delay)?;
        self.update_bw(buffer, delay)?;
        self.update_display(delay)?;
        self.sleep(delay)
    }

    /// Update red buffer and refresh the display in one command
    pub fn update_and_display_red(
        &mut self,
        buffer: &[u8],
        delay: &mut impl DelayNs,
    ) -> Result<(), DisplayError> {
        self.init(delay)?;
        self.update_red(buffer, delay)?;
        self.update_display(delay)?;
        self.sleep(delay)
    }

    /// Update both black & white and red buffers and refresh the display in one command
    pub fn update_and_display(
        &mut self,
        bw_buffer: &[u8],
        red_buffer: &[u8],
        delay: &mut impl DelayNs,
    ) -> Result<(), DisplayError> {
        self.init(delay)?;
        self.update(bw_buffer, red_buffer, delay)?;
        self.update_display(delay)?;
        self.sleep(delay)
    }

    fn write_bw_ram(&mut self, buffer: &[u8]) -> Result<(), DisplayError> {
        self.set_ram_counter(0, 0)?;
        self.interface
            .cmd_with_data(cmd::Cmd::WRITE_BW_DATA, buffer)
    }

    fn write_red_ram(&mut self, buffer: &[u8]) -> Result<(), DisplayError> {
        self.set_ram_counter(0, 0)?;
        self.interface
            .cmd_with_data(cmd::Cmd::WRITE_RED_DATA, buffer)
    }

    fn update_display(&mut self, delay: &mut impl DelayNs) -> Result<(), DisplayError> {
        self.interface.cmd_with_data(
            cmd::Cmd::DISPLAY_UPDATE_CTRL2,
            &[flag::Flag::DISPLAY_MODE_LOAD_TEMP_1],
        )?;
        self.interface.cmd(cmd::Cmd::MASTER_ACTIVATE)?;
        self.interface.wait_until_idle(delay);
        Ok(())
    }

    fn use_full_frame(&mut self) -> Result<(), DisplayError> {
        self.set_ram_area(0, 0, WIDTH - 1, HEIGHT - 1)?;
        self.set_ram_counter(0, 0)
    }

    fn set_ram_area(
        &mut self,
        start_x: u16,
        start_y: u16,
        end_x: u16,
        end_y: u16,
    ) -> Result<(), DisplayError> {
        self.interface.cmd_with_data(
            cmd::Cmd::SET_RAMXPOS,
            &[(start_x >> 3) as u8, (end_x >> 3) as u8],
        )?;

        self.interface.cmd_with_data(
            cmd::Cmd::SET_RAMYPOS,
            &[
                (start_y & 0xFF) as u8,
                ((start_y >> 8) & 0x01) as u8,
                (end_y & 0xFF) as u8,
                ((end_y >> 8) & 0x01) as u8,
            ],
        )?;
        Ok(())
    }

    fn set_ram_counter(&mut self, x: u32, y: u32) -> Result<(), DisplayError> {
        self.interface
            .cmd_with_data(cmd::Cmd::SET_RAMX_COUNTER, &[(x >> 3) as u8])?;

        self.interface.cmd_with_data(
            cmd::Cmd::SET_RAMY_COUNTER,
            &[(y & 0xFF) as u8, ((y >> 8) & 0x01) as u8],
        )?;
        Ok(())
    }
}
impl<SPI, BSY, DC, RST> Ssd1680Driver for WeActStudio2in13<SPI, BSY, DC, RST>
where
    SPI: SpiDevice,
    BSY: InputPin,
    DC: OutputPin,
    RST: OutputPin,
{
    fn init(&mut self, delay: &mut impl DelayNs) -> Result<(), DisplayError> {
        debug!("powering up display");

        self.interface.hard_reset(delay);

        for step in INIT_SEQUENCE {
            debug!("init step: {:?}", step);
            match *step {
                InitStep::SWReset => {
                    self.interface.cmd(cmd::Cmd::SW_RESET)?;
                }
                InitStep::DelayMs(ms) => {
                    delay.delay_ms(u32::from(ms));
                }
                InitStep::WaitUntilIdle => {
                    self.interface.wait_until_idle(delay);
                }
                InitStep::Cmd(c) => {
                    self.interface.cmd(c)?;
                }
                InitStep::CmdData(c, d) => {
                    self.interface.cmd_with_data(c, d)?;
                }
                InitStep::DriverControl => {
                    let h = HEIGHT.saturating_sub(1);
                    let low = (h & 0xFF) as u8;
                    let high = ((h >> 8) & 0x01) as u8;
                    self.interface
                        .cmd_with_data(cmd::Cmd::DRIVER_OUTPUT_CTRL, &[low, high, 0x00])?;
                }
                InitStep::UseFullFrame => {
                    self.use_full_frame()?;
                }
            }
        }

        self.interface.wait_until_idle(delay);
        Ok(())
    }

    fn sleep(&mut self, delay: &mut impl DelayNs) -> Result<(), DisplayError> {
        debug!("powering down display");
        self.interface
            .cmd_with_data(cmd::Cmd::DEEP_SLEEP, &[0x01])?;
        delay.delay_ms(1);
        Ok(())
    }

    fn update_bw(&mut self, buffer: &[u8], delay: &mut impl DelayNs) -> Result<(), DisplayError> {
        self.write_bw_ram(buffer)?;
        self.interface.wait_until_idle(delay);
        Ok(())
    }

    fn update_red(&mut self, buffer: &[u8], delay: &mut impl DelayNs) -> Result<(), DisplayError> {
        self.write_red_ram(buffer)?;
        self.interface.wait_until_idle(delay);
        Ok(())
    }

    fn update(
        &mut self,
        bw_buffer: &[u8],
        red_buffer: &[u8],
        delay: &mut impl DelayNs,
    ) -> Result<(), DisplayError> {
        self.write_bw_ram(bw_buffer)?;
        self.write_red_ram(red_buffer)?;
        self.interface.wait_until_idle(delay);
        Ok(())
    }

    fn clear_bw_ram(&mut self) -> Result<(), DisplayError> {
        let color = Color::White.get_byte_value();
        self.interface.cmd(cmd::Cmd::WRITE_BW_DATA)?;
        self.interface
            .data_x_times(color, u32::from(WIDTH).div_ceil(8) * u32::from(HEIGHT))?;
        Ok(())
    }

    fn clear_red_ram(&mut self) -> Result<(), DisplayError> {
        let color = Color::White.inverse().get_byte_value();
        self.interface.cmd(cmd::Cmd::WRITE_RED_DATA)?;
        self.interface
            .data_x_times(color, u32::from(WIDTH).div_ceil(8) * u32::from(HEIGHT))?;
        Ok(())
    }

    fn begin(&mut self, delay: &mut impl DelayNs) -> Result<(), DisplayError> {
        self.interface.hard_reset(delay);
        self.sleep(delay)
    }
}

/// Graphics buffer for 2.13in panel
pub struct Display2in13 {
    buffer: [u8; buffer_len(WIDTH as usize, HEIGHT as usize)],
    rotation: DisplayRotation,
    is_inverted: bool,
}

impl Display2in13 {
    /// Create a black & white display buffer
    pub fn bw() -> Self {
        Self {
            buffer: [Color::White.get_byte_value(); buffer_len(WIDTH as usize, HEIGHT as usize)],
            rotation: DisplayRotation::default(),
            is_inverted: false,
        }
    }

    /// Create a red display buffer
    pub fn red() -> Self {
        Self {
            buffer: [Color::White.inverse().get_byte_value();
                buffer_len(WIDTH as usize, HEIGHT as usize)],
            rotation: DisplayRotation::default(),
            is_inverted: false,
        }
    }
}

impl DrawTarget for Display2in13 {
    type Error = DisplayError;
    type Color = BinaryColor;

    fn draw_iter<I>(&mut self, pixels: I) -> Result<(), Self::Error>
    where
        I: IntoIterator<Item = Pixel<Self::Color>>,
    {
        for p in pixels.into_iter() {
            self.draw_helper(WIDTH.into(), HEIGHT.into(), p)?;
        }
        Ok(())
    }
}

impl OriginDimensions for Display2in13 {
    fn size(&self) -> Size {
        //if display is rotated 90 deg or 270 then swap height and width
        match self.rotation() {
            DisplayRotation::Rotate0 | DisplayRotation::Rotate180 => {
                Size::new(WIDTH.into(), HEIGHT.into())
            }
            DisplayRotation::Rotate90 | DisplayRotation::Rotate270 => {
                Size::new(HEIGHT.into(), WIDTH.into())
            }
        }
    }
}

impl Display for Display2in13 {
    fn buffer(&self) -> &[u8] {
        &self.buffer
    }

    fn get_mut_buffer(&mut self) -> &mut [u8] {
        &mut self.buffer
    }

    fn set_rotation(&mut self, rotation: DisplayRotation) {
        self.rotation = rotation;
    }

    fn rotation(&self) -> DisplayRotation {
        self.rotation
    }

    fn is_inverted(&self) -> bool {
        self.is_inverted
    }
}

#[cfg(test)]
mod tests {
    use super::{Display, Display2in13, DisplayRotation, HEIGHT, WIDTH};
    use crate::color::{Black, Color};
    use crate::displays::{find_position, outside_display};
    use embedded_graphics::{prelude::*, primitives::Line, primitives::PrimitiveStyle};

    #[test]
    fn buffer_clear() {
        let mut display = Display2in13::bw();

        for &byte in display.buffer().iter() {
            assert_eq!(byte, Color::White.get_byte_value());
        }

        display.clear_buffer(Color::Black);

        for &byte in display.buffer().iter() {
            assert_eq!(byte, Color::Black.get_byte_value());
        }
    }

    #[test]
    fn rotation_overflow() {
        let width = WIDTH as u32;
        let height = HEIGHT as u32;
        test_rotation_overflow(width, height, DisplayRotation::Rotate0);
        test_rotation_overflow(width, height, DisplayRotation::Rotate90);
        test_rotation_overflow(width, height, DisplayRotation::Rotate180);
        test_rotation_overflow(width, height, DisplayRotation::Rotate270);
    }

    fn test_rotation_overflow(width: u32, height: u32, rotation: DisplayRotation) {
        let max_value = width.div_ceil(8) * height;
        for x in 0..(width + height) {
            //limit x because it runs too long
            for y in 0..u32::MAX {
                if outside_display(Point::new(x as i32, y as i32), width, height, rotation) {
                    break;
                } else {
                    let (idx, _) = find_position(x, y, width, height, rotation);
                    assert!(idx < max_value, "{idx} !< {max_value}",);
                }
            }
        }
    }

    #[test]
    fn graphics_rotation_0() {
        let mut display = Display2in13::bw();

        let _ = Line::new(Point::new(0, 0), Point::new(7, 0))
            .into_styled(PrimitiveStyle::with_stroke(Black, 1))
            .draw(&mut display);

        let buffer = display.buffer();

        assert_eq!(buffer[0], Color::Black.get_byte_value());

        for &byte in buffer.iter().skip(1) {
            assert_eq!(byte, Color::White.get_byte_value());
        }
    }
}
